let FilmJson= [
  {
      id: 1,
      franquia: 'Friday the 13th',
      name: 'Sexta Feira 13',
      img: 'img/SextaFeira13.png',
      notaimdb: 6.4,
      link_trailer: 'https://www.youtube.com/watch?v=7tSHowaHuFY',
      link_film: 'https://pluto.tv/en/on-demand/movies/friday-the-13th-2009-1969-1-1',
      sinopse:'Um ladrão persegue e assasina a um grupo de conselheiros num acampamento onde morreu uma criança anos atrais.',
    },{
      id: 2,
      franquia: 'Friday the 13th',
      name: 'Sexta Feira 13: Parte 2',
      img: 'img/SextaFeira132.png',
      notaimdb: 6.1,
      link_trailer: 'https://www.youtube.com/watch?v=1E1jSABnvcg',
      link_film: 'https://pluto.tv/en/on-demand/movies/friday-the-13th-part-ii-1969-1-1',
      sinopse:'Cinco anos após o massacre no acampamento Cristal Lake, investidores abrem um novo campo na margem do lago, não muito distante do local fatídico. Mas os jovens do novo campo também começam a sofrer ataques brutais.',
    },{
      id: 3,
      franquia: 'Friday the 13th',
      name: 'Sexta Feira 13: Parte 3',
      img: 'img/SextaFeira133.png',
      notaimdb: 5.6,
      link_trailer: 'https://www.youtube.com/watch?v=SNcHEzp0u-w',
      link_film: 'https://pluto.tv/en/on-demand/movies/friday-the-13th-part-iii-1969-1-1',
      sinopse:'Quando um grupo de jovens procura a paz e a tranquilidade da floresta ao redor de Cristal Lake, Jason encontra novas presas para abater.',
    },{
      id: 4,
      franquia: 'Friday the 13th',
      name: 'Sexta Feira 13: Parte 4',
      img: 'img/SextaFeira134.png',
      notaimdb: 6,
      link_trailer: 'https://www.youtube.com/watch?v=mHoMXxBo3sU',
      link_film: 'https://pluto.tv/en/on-demand/movies/friday-the-13th-part-ivthe-final-chapter-1969-1-1',
      sinopse:'Quando uma nova série de violentos assassinatos começa a ocorrer, os moradores dos arredores de Cristal Lake descobrem que Jason pode ainda estar vivo.',
    },{
      id: 5,
      franquia: 'Friday the 13th',
      name: 'Sexta Feira 13: Parte 5',
      img: 'img/SextaFeira135.png',
      notaimdb: 4.7,
      link_trailer: 'https://www.youtube.com/watch?v=A5xL_F1A1p0',
      link_film: 'https://pluto.tv/en/on-demand/movies/friday-the-13th-part-v-a-new-beginning-1969-1-1',
      sinopse:'Ainda atormentado por seu passado, Tommy Jarvis quem quando criança matou Jason Voorhees, se pergunta se o serial killer está conectado a uma série de assassinatos brutais que ocorrem onde ele vive agora.',
    },{
      id: 6,
      franquia: 'Friday the 13th',
      name: 'Sexta Feira 13: Parte 6',
      img: 'img/SextaFeira136.png',
      notaimdb: 6,
      link_trailer: 'https://www.youtube.com/watch?v=Q3dUOdrAmvA',
      link_film: 'https://pluto.tv/en/on-demand/movies/friday-the-13th-part-vi-jason-lives-1969-1-1',
      sinopse:'Tommy Jarvis ficou traumatizado após a sua mãe e amigos serem mortos por Jason. Querendo assegurar-se da sua morte, desenterra o cadáver para o queimar, mas um relâmpago dá nova vida ao monstro, preparando-o para um novo massacre.',
    },{
      id: 7,
      franquia: 'Friday the 13th',
      name: 'Sexta Feira 13: Parte 7',
      img: 'img/SextaFeira137.png',
      notaimdb: 5.2,
      link_trailer: 'https://www.youtube.com/watch?v=lrWUuX9XZ1g',
      link_film: 'https://pluto.tv/en/on-demand/movies/friday-the-13th-part-viithe-new-blood-1969-1-1',
      sinopse:'Tina é uma jovem com poderes telecinéticos que matou o pai em Crystal Lake, sem querer. Após anos de terapia, o psicólogo propõe-lhe visitar o local. Infelizmente, as habilidades psíquicas dela despertam Jason, que jazia no fundo do lago.',
    },{
      id: 8,
      franquia: 'Friday the 13th',
      name: 'Sexta Feira 13: Parte 8',
      img: 'img/SextaFeira138.png',
      notaimdb: 4.5,
      link_trailer: 'https://www.youtube.com/watch?v=MjD6L3ASjfA',
      link_film: 'https://pluto.tv/en/on-demand/movies/friday-the-13th-part-viii-jason-takes-manhattan-1969-1-1',
      sinopse:'Despertado pela descarga de um cabo submerso, Jason toma carona num iate em excursão de estudantes, matando os jovens de todas as formas possíveis, por fim desembarcando justamente em Nova York, espalhando horror.',
    }
]